version: "3.9"
services:
  backend:
    # Will be built in Step 2
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data/uploads:/app/data/uploads
    # command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: ["5173:80"]
    depends_on:
      - backend