name: CI

on:
  push:
    branches: [ "main", "week-*", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api:
    name: Backend (lint/typecheck + schemas)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt ruff mypy pytest
      - name: Ruff (lint)
        run: ruff check app
      - name: Mypy (types)
        run: mypy app || true   # keep lenient in Week 1
      - name: Smoke tests (pytest placeholder)
        run: |
          echo "from fastapi.testclient import TestClient; from app.main import app; c=TestClient(app); assert c.get('/v1/health').status_code==200" > tests/test_smoke.py
          pytest -q
      - name: Generate JSON Schemas
        env:
          PYTHONPATH: .
        run: |
          python -m app.utils.generate_schema
      - name: Upload schema artifact
        uses: actions/upload-artifact@v4
        with:
          name: schemas-json
          path: backend/docs/schema/*.json

  ui:
    name: Frontend (typecheck + build)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Install
        run: npm ci
      - name: Typecheck
        run: npx tsc --noEmit
      - name: Build
        run: npm run build
