name: CI
on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "CI placeholder – expand in Week 1 Day 6"
