name: CI
on:
  pull_request:
  push:
    branches: [dev, main]

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bootstrap check
        run: echo "Bootstrapped CI — add real checks in Week 1 Day 5–7"
